config/routes.rb
Opcut::Application.routes.draw do
  resources :cut_links do
    member do
      get 'redirect'
    end
  end

  get "pages/home"

  root :to => 'cut_links#index'

  match ':id' => 'cut_links#redirect'

end

app/models/cut_link.rb
class CutLink < ActiveRecord::Base
  attr_accessible :cut, :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cut_links_controller.rb
class CutLinksController < ApplicationController
  # GET /cut_links
  # GET /cut_links.json
  def index
    @cut_links = CutLink.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cut_links }
    end
  end

  # GET /cut_links/1
  # GET /cut_links/1.json
  def show
    @cut_link = CutLink.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cut_link }
    end
  end

  # GET /cut_links/new
  # GET /cut_links/new.json
  def new
    @cut_link = CutLink.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cut_link }
    end
  end

  # GET /cut_links/1/edit
  def edit
    @cut_link = CutLink.find(params[:id])
  end

  # POST /cut_links
  # POST /cut_links.json
  def create
    @cut_link = CutLink.new(params[:cut_link])

    respond_to do |format|
      if @cut_link.save
        format.html { redirect_to @cut_link, notice: 'Cut link was successfully created.' }
        format.json { render json: @cut_link, status: :created, location: @cut_link }
      else
        format.html { render action: "new" }
        format.json { render json: @cut_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cut_links/1
  # PUT /cut_links/1.json
  def update
    @cut_link = CutLink.find(params[:id])

    respond_to do |format|
      if @cut_link.update_attributes(params[:cut_link])
        format.html { redirect_to @cut_link, notice: 'Cut link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cut_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cut_links/1
  # DELETE /cut_links/1.json
  def destroy
    @cut_link = CutLink.find(params[:id])
    @cut_link.destroy

    respond_to do |format|
      format.html { redirect_to cut_links_url }
      format.json { head :no_content }
    end
  end

  # GET /1
  # GET /cut_links/1/redirect
  # GET /cut_links/1/redirect.json
  def redirect
    @cut_links = CutLink.find(params[:id])

    respond_to do |format|
      format.html { redirect_to @cut_links.link, :status => :moved_permanently }
      format.json { render :json => @cut_links } # What does it mean to redirect using json?
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Startowa"
    @kod = ('a'..'z').to_a.shuffle[0..7].join
    @adres = "jojo"

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    x_title = "Bez tytulu"
    if @title.nil?
      x_title
    else
      "#{@title}"
    end
  end

  def kod
    x_kod = "Bez koda"
    if @kod.nil?
      x_kod
    else
      "#{@kod}"
    end
  end

  # Returns the complete URL used for this request.
  def adres
    x_adres = "Bez adresu"
      if @adres.nil?
        x_adres
      else
        "#{@adres}"
      end
  end


end

app/helpers/cut_links_helper.rb
module CutLinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper

end

app/views/cut_links/_form.html.erb
<%= form_for(@cut_link) do |f| %>
  <% if @cut_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cut_link.errors.count, "error") %> prohibited this cut_link from being saved:</h2>

      <ul>
      <% @cut_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :cut %><br />
    <%= f.text_field :cut, :value => ('a'..'z').to_a.shuffle[0..7].join %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cut_links/edit.html.erb
<h1>Editing cut_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @cut_link %> |
<%= link_to 'Back', cut_links_path %>

app/views/cut_links/index.html.erb
<h1>Witamy</h1>

<table>
  <tr>
    <th>Skrot:</th>
    <th>Link:</th>

    <th></th>
    <th></th>
  </tr>

<% @cut_links.each do |cut_link| %>
  <tr>
    <td style="background-color: #cccccc;"><strong><%= "http://" + request.env["HTTP_HOST"] + "/" %><%= cut_link.id %></strong></td>
    <td><%= cut_link.link %></td>
    <td><%= link_to 'Edycja', edit_cut_link_path(cut_link) %></td>
    <td><%= link_to 'Usuń', cut_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cut link', new_cut_link_path %>

app/views/cut_links/new.html.erb
<h1>New cut_link</h1>

<%= render 'form' %>

<%= link_to 'Back', cut_links_path %>

app/views/cut_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Link:</b>
  <%= @cut_link.link %>
</p>

<p>
  <b>Cut:</b>
  <%= @cut_link.cut %>
</p>


<%= link_to 'Edit', edit_cut_link_path(@cut_link) %> |
<%= link_to 'Back', cut_links_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Witamy w drugim sposobie obcinania URL</h1>
<p>Twoj skrot to <strong> <%= "http://" + request.env["HTTP_HOST"] + "/" + kod %> </strong> </p>
<p>jesli uwazasz ze jest nie ladny nacisnij F5</p>
<p> w przeciwnym wypadku wpisz gdzie ma on kierowac</p>
<%= request.env["HTTP_REFERER"] %>